service: scrape-twitter

provider:
  name: aws
  runtime: python3.6
  region: us-west-2

functions:
  cron:
    handler: twitter_worker.main
    events:
      # Invoke Lambda function every 10 minutes
      - schedule: rate(10 minutes)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux